-dontwarn org.tobi29.scapes.engine.android.ScapesEngineView$attach$new$1$2$1
-dontwarn org.tobi29.scapes.engine.android.ScapesEngineView$attach$new$1$2
-dontwarn org.tobi29.scapes.engine.android.ScapesEngineView$attach$new$1$2$1